---
extends:
  - airbnb-base
  - plugin:import/warnings
  - plugin:vue/essential
  - plugin:vue-pug/essential
  - plugin:jest-formatting/strict

env:
  browser: true
  jest: true

plugins:
  - vue
  - import
  - jest-formatting

settings:
  import/resolver:
    webpack:
      node: { }

rules:
  sort-imports:
    - error
    - ignoreDeclarationSort: true
  no-multiple-empty-lines: 0
  arrow-parens: 0
  max-classes-per-file: 0
  import/extensions: 0
  import/no-cycle:
    - error
    - maxDepth: 2
  import/order: off
  import/newline-after-import:
    - error
    - count: 2
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: "*"
      next: return
    - blankLine: always
      prev: "*"
      next: export
  no-param-reassign:
    - 2
    - props: false
  no-console:
    - error
    - allow:
      - warn
      - error
  object-curly-newline:
    - error
    - ImportDeclaration:
        minProperties: 1
        multiline: true
        consistent: true
      ObjectExpression:
        consistent: true
        minProperties: 3
  require-await:
    - error
  vue/multi-word-component-names: 0
  vue/padding-line-between-blocks: 2
  vue/no-potential-component-option-typo: 2
  vue/new-line-between-multi-line-property:
    - error
    - minLineOfMultilineProperty: 2
  vue/prop-name-casing:
    - error
    - camelCase
  vue/order-in-components:
    - error
    - order:
        - el
        - name
        - delimiters
        - extends
        - mixins
        - directives
        - components
        - inheritAttrs
        - props
        - emits
        - setup
        - data
        - computed
        - methods
        - filters
        - watch
        - LIFECYCLE_HOOKS
        - ROUTER_GUARDS
        - template
        - render

parser: "vue-eslint-parser"
parserOptions:
  requireConfigFile: false
  parser:
    js: "@babel/eslint-parser"

globals:
  inject: false
